name: SonarCloud Analysis
on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline  # Trigger analysis on this branch
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline  # Trigger analysis on PRs to this branch

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          cache: 'npm'

      - name: Install dependencies (Backend)
        run: |
          cd project-backend
          npm install

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Run tests and generate coverage (Backend)
        run: |
          cd project-backend
          npm test -- --coverage

      - name: Run tests and generate coverage (Frontend)
        run: |
          cd frontend
          npm test -- --coverage

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # SonarCloud token
        with:
          args: >
            -Dsonar.branch.name=l00187927-WA-Jira18-CIPipeline  # Analyze this branch